version: '3.8'

services:
  mailserver:
    build: .
    container_name: mailserver
    hostname: mail
    domainname: fungigrotto.com
    restart: always
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - maildata:/var/mail
      - mailconfig:/etc/postfix
    environment:
      - HOSTNAME=mail.fungigrotto.com
      - DOMAIN=fungigrotto.com
    networks:
      - mailnet

volumes:
  maildata:
  mailconfig:

networks:
  mailnet:
    driver: bridge
